title: Title
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://janbrasna.github.io/testssl.sh-jekyll

aux_links:
  Template Repository: https://github.com/janbrasna/testssl.sh-jekyll
