title: testssl.sh
description: CLI tool to check TLS/SSL ciphers, protocols, their cryptographic flaws and more.
theme: just-the-docs

url: https://janbrasna.github.io/

plugins:
  - jekyll-default-layout

aux_links:
  Edit on GitHub: https://github.com/janbrasna/testssl.sh-jekyll
